### ISSUE TITLE
[midea] Error logging in to Midea Cloud

### ISSUE THREAD

**Issue by boboxx** [kovapatrik/homebridge-midea-platform#10]
I just installed the plugin and added my devices. I use NetHomePlus on my iPhone so thatès what I selected from the drop down but when I resstart the service I get: 

[9/21/2023, 2:09:34 PM] [midea] Error logging in to Midea Cloud: Error: Failed to send request to https://mapp.appsmb.com/v1/user/login/id/get.

I have validated my user and password and I know they are correct! These are also the name user/password used in Homebridge Midea Air plugin and itès working fine there.

**Comment by kovapatrik** [comment]
I haven't tested any other apps except MSmartHome, so Iexpected bugs about it.

I will add more logs tomorrow at the login so we can debug it.

**Comment by dkerr64** [comment]
I confirm that NetHomePlus login method fails.  I tried this first because ironically another plugin I am working with fails with MSmartHome method but works with NetHomePlus!!  As I have both apps installed, I was able to simply switch to MSmartHome and it worked.

Let me know if you need assistance debugging.

**Comment by kovapatrik** [comment]
I've just published an update which may solve the login issue. Can you check it?

**Comment by dkerr64** [comment]
Nope, not yet...

```
[9/24/2023, 1:56:28 PM] [homebridge-midea-platform] Executed didFinishLaunching callback
[9/24/2023, 1:56:28 PM] Homebridge v1.6.1 (HAP v0.11.1) (homebridge-midea-platform) is running on port 41080.
[9/24/2023, 1:56:29 PM] [homebridge-midea-platform] Error while sending request to https://mapp.appsmb.com/v1/user/login/id/get: {"msg":"Sign illegal.","errorCode":"3301"}
[9/24/2023, 1:56:29 PM] [homebridge-midea-platform] Error while sending request to https://mapp.appsmb.com/v1/user/login/id/get: {"msg":"Sign illegal.","errorCode":"3301"}
[9/24/2023, 1:56:29 PM] [homebridge-midea-platform] Error while sending request to https://mapp.appsmb.com/v1/user/login/id/get: {"msg":"Sign illegal.","errorCode":"3301"}
[9/24/2023, 1:56:29 PM] [homebridge-midea-platform] Error logging in to Midea Cloud: Error: Failed to send request to https://mapp.appsmb.com/v1/user/login/id/get.
    at NetHomePlusCloud.apiRequest (/home/david/github/homebridge-midea-platform/src/core/MideaCloud.ts:80:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NetHomePlusCloud.getLoginId (/home/david/github/homebridge-midea-platform/src/core/MideaCloud.ts:84:22)
    at NetHomePlusCloud.login (/home/david/github/homebridge-midea-platform/src/core/MideaCloud.ts:96:22)
```

**Comment by boboxx** [comment]
Any progress on this?

**Comment by dkerr64** [comment]
I spent some time looking at the code today.  I conclude that NetHomePlus login has never worked, was in fact never implemented.  Looking at the [midea_ac_lan](https://github.com/georgezhao2010/midea_ac_lan/blob/master/custom_components/midea_ac_lan/midea/core/cloud.py) python on which this is based, I believe that it doesn't support NetHomePlus login either... they include it in the list of clouds but as far as I can tell, it is not implemented.  Can anyone test whether it works? (I don't have home assistant installed).

The [midea-beautiful-air](https://github.com/nbogojevic/midea-beautiful-air) project and [homebridge-midea-air](https://github.com/hillaliy/homebridge-midea-air) project both support NetHomePlus login.  I have confirmed that the first of these definitely works (it has a useful command line tool).

Looking at the code for this plugin and comparing to these two, and that the error returned is
`{"msg":"Sign illegal.","errorCode":"3301"}` I believe that the problem is missing signing key.  There is a constant which needs to be md5 encoded.  You have these in MideaSecurity.ts but they are commented out and never used...
```
// private static readonly SIGN_KEY = Buffer.from('xhdiwjnchekd4d512chdjx5d8e4c394D2D7S', 'utf-8');
// public static readonly ENC_KEY = createHash('md5').update(this.SIGN_KEY).digest();
```
So there is work to be done to implement NetHome Plus login method using this signing key.

That is as far as I have got, I will not have time to work on this further for a while.

**Comment by kovapatrik** [comment]
Thanks for looking into it! The current implementation is trying to replicate the midea-beautiful-air solution, but I didn't looked that deep into the function (like the creation of the sign). I hope I will have time in the following days to check it.

**Comment by kovapatrik** [comment]
I checked on it now, but the two commented line is not related to NetHome Plus or any other cloud connection. Those were used for the local TCP connection.

**Comment by kovapatrik** [comment]
I've created a PR to your forked repository, which solves the NetHome Plus login issue. I can't test if the other parts of the API will work or not because my devices are not in the NetHome Plus app, but I think it should work.

Btw, do you have permission to create a branch on my repository? It would really ease the development of the plugin if we work on a single repository (I'm not used to develop on forks, but it's counter intuitive that I have to create a PR to your branch which is a PR to my repo).

**Comment by dkerr64** [comment]
Confirm that NetHome Plus login now works.  Thanks for fixing that.

**Comment by dkerr64** [comment]
> Btw, do you have permission to create a branch on my repository? It would really ease the development of the plugin if we work on a single repository (I'm not used to develop on forks, but it's counter intuitive that I have to create a PR to your branch which is a PR to my repo).

No, I don't have permissions to do that.  I don't know GitHub well enough to know if you could give me those permissions, but pull requests is the way that it is expected to be done.  I think your PR into my development branch was quite appropriate way to ask me to test it.

**Comment by kovapatrik** [comment]
@boboxx It's released now, can you check it out sometimes if it works or not?

**Comment by boboxx** [comment]
Just gave it a try and it's still not working. It looks like it's able to log in but it still has errors and put HB in a reboot loop:

10/14/2023, 8:06:28 PM] [midea] Logged in to Midea Cloud.
[10/14/2023, 8:06:28 PM] [midea] Logged in to Midea Cloud.
[10/14/2023, 8:06:29 PM] Error: Failed to send request to https://mapp.appsmb.com/v1/user/login.
    at NetHomePlusCloud.apiRequest (/usr/lib/node_modules/homebridge-midea-platform/src/core/MideaCloud.ts:284:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NetHomePlusCloud.login (/usr/lib/node_modules/homebridge-midea-platform/src/core/MideaCloud.ts:289:22)
    at MideaPlatform.addDevice (/usr/lib/node_modules/homebridge-midea-platform/src/platform.ts:251:7)
[10/14/2023, 8:06:29 PM] Got SIGTERM, shutting down Homebridge...
[10/14/2023, 8:06:29 PM] Error: Failed to send request to https://mapp.appsmb.com/v1/user/login.
    at NetHomePlusCloud.apiRequest (/usr/lib/node_modules/homebridge-midea-platform/src/core/MideaCloud.ts:284:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NetHomePlusCloud.login (/usr/lib/node_modules/homebridge-midea-platform/src/core/MideaCloud.ts:289:22)
    at MideaPlatform.addDevice (/usr/lib/node_modules/homebridge-midea-platform/src/platform.ts:251:7)
[10/14/2023, 8:06:29 PM] Error: Failed to send request to https://mapp.appsmb.com/v1/user/login.
    at NetHomePlusCloud.apiRequest (/usr/lib/node_modules/homebridge-midea-platform/src/core/MideaCloud.ts:284:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NetHomePlusCloud.login (/usr/lib/node_modules/homebridge-midea-platform/src/core/MideaCloud.ts:289:22)
    at MideaPlatform.addDevice (/usr/lib/node_modules/homebridge-midea-platform/src/platform.ts:251:7)
[10/14/2023, 8:06:30 PM] [midea] Discovered device: {"ip":"10.1.10.7","port":6444,"id":30786332132192,"model":"00000Q13","sn":"000000P00000000000A23748ECA40000","name":"net_ac_ECA4","type":172,"version":3}
[10/14/2023, 8:06:30 PM] [midea] Adding new accessory: Unit3
[10/14/2023, 8:06:31 PM] [midea] Logged in to Midea Cloud.

**Comment by kovapatrik** [comment]
I had the same error before. You sure you have the latest version? It should be v0.3.0.

Note: you shouldn't post the IP of your device anywhere.

**Comment by boboxx** [comment]
Yes I'm on V0.3.0.

It's a private IP, I'm ok :)

**Comment by dkerr64** [comment]
@boboxx thank you for the log.  I think I know what is going on... you state you have 4 devices on your network.  Because of the asynchronous nature of device discovery, this could result in 4 almost simultaneous requests to login.  We only want to do it once because as your log shows, bad things happen if multiple attempts are allowed.

The login code needs to be protected with a semaphore so that one login attempt is completed before others are attempted (and skipped if already logged in).  I had added code for this to the base class, but when @kovapatrik fixed the NetHome Plus login he replaced the base login function with a new one specific to NetHome Plus and did not include the semaphore protection.

The original code was working for me because I only have one Midea device.

I have added the necessary code in PR #18 which hopefully will get things working for you once @kovapatrik  merges it.

**Comment by kovapatrik** [comment]
Yes, you are right, I've completely forgot about the semaphore. I hope it will solve the issue.

@boboxx  it is released now.

**Comment by boboxx** [comment]
Sweet!! it's working!!!! Thank you :)

**Comment by kovapatrik** [comment]
Cool! Thanks for the fix @dkerr64!
