### ISSUE TITLE
Add supporto for Heat Pump Wi-Fi Controller (C3)

### ISSUE THREAD

**Issue by fagallo** [kovapatrik/homebridge-midea-platform#107]
Please add support for Heat Pump Wi-Fi Controller ( type C3 ). It's very popular, sold under different brands.

Thanks a lot.

**Comment by kovapatrik** [comment]
Can you please describe what feature would you need?

**Comment by fagallo** [comment]
Heat pump is not supported at this time. You only support : Air Conditioner	(AC); Dehumidifier	(A1); Electric Water Heater (E2); Gas Water Heater (E3); Fan (FA).

I request if you can support  Heat Pump Wi-Fi Controller (C3). It’s supported in HA by @georgezhao2010 , and your plugin is based on work of him.

Thanks

**Comment by kovapatrik** [comment]
I'm just asking what features would you need? What do you want to access from Apple Home? There are a lot of features in the offiical application (I would guess), and as I don't know what are these features and how do they work, I want to ask you to provide me some input about these as I can't implement features I don't know about.

**Comment by fagallo** [comment]
The most important (essential) feature are :

1) Switch for:
- power ON/OFF *
- Silent mode on/off *
- Climate curve on/off *
- ECO mode on/off *

2) Sensor for :
- Compressor Status 
- external temperatures *
- internal temperature *
- tank temperature 
- energy consumption
- total energy
- error code

3) Thermostat card

* It’s for use in apple home

There are other feature that you can implement, but these are the minimum to operate the heat pump.

I remain available for any clarification.

**Comment by kovapatrik** [comment]
By looking [at this table](https://github.com/georgezhao2010/midea_ac_lan/blob/master/doc/C3.md#extra-entities), I came to a conclusion I will separate settings like this:

```json
 "zone1": {
                  "title": "Zone 1 accessory",
                  "description": "Toggles if the zone 1 accessory is created with the accessory.",
                  "type": "boolean"
                },
                "zone2": {
                  "title": "Zone 2 accessory",
                  "description": "Toggles if the zone 2 accessory is created with the accessory.",
                  "type": "boolean"
                },
                "waterHeater": {
                  "title": "Water Heater accessory",
                  "description": "Toggles if the water heater accessory is created with the accessory.",
                  "type": "boolean"
                },
                "ecoSwitch": {
                  "title": "Eco Mode Switch",
                  "description": "Toggles if the ECO mode switch is created with the accessory.",
                  "type": "boolean"
                },
                "silentSwitch": {
                  "title": "Silent Mode Switch",
                  "description": "Toggles if the silent mode switch is created with the accessory.",
                  "type": "boolean"
                },
                "tbhSwitch": {
                  "title": "TBH Mode Switch",
                  "description": "Toggles if the TBH mode switch is created with the accessory.",
                  "type": "boolean"
                },
                "disinfectSwitch": {
                  "title": "Disinfect Mode Switch",
                  "description": "Toggles if the disinfect mode switch is created with the accessory.",
                  "type": "boolean"
                }
```

Is this okay with you? Also, I might need you to get an understanding of the sensors and switches. For example, I want some logic, if the water heater accessory is created, then all of the things which are somehow in connection with the water heater (like the `dhw` settings, if I understand correctly) should be created with it. Can you provide some grouping like this for `zone1`, `zone2` and `waterHeater`?

**Comment by kovapatrik** [comment]
Or maybe a more clarified question: which services from the linked table should be created with `zone1`, `zone2` or `waterHeater`?

**Comment by kovapatrik** [comment]
I might totally misunderstood this, and all of these (`zone1`, `zone2`, `waterHeater`) should be created by default and there shouldn't be options to disable them. I totally don't understand how this should work, so I would like to rely on you in these questions.

**Comment by fagallo** [comment]
I have a simple heating system with only one zone and without tank. But this in only my case.
I will go to collect more information and I will go to write you tomorrow.

Sorry for English.

**Comment by kovapatrik** [comment]
Thank you! So my initial intuition about this was not entirely incorrect.

**Comment by fagallo** [comment]
> I might totally misunderstood this, and all of these (zone1, zone2, waterHeater) should be created by default and there shouldn't be options to disable them. I totally don't understand how this should work, so I would like to rely on you in these questions.

There are heat system with one zone or two zone. In my case Is disabled on the Wifi Controller (where you enter the parameters). In the same way there can be systems without tank and consequently therefore fast_dhw and water_heater is disabled ( always my case). Tank is for domestic hot water, zone 1/2 is , for example, for a two-level house.


This is the variable in home assistant :

￼

There is another value, important for trigger, that I don't know why it doesn't work, the room_temperature.


I n the end the plug-in takes, more or less, the data that is on the official app. 

￼

￼

At this link https://world.clivet.it/openDocs?c=KeJvMXkNddkYQb010f6sKA%3D%3D&e=Ny4kuAP%2F5XE%3D&d=86DmsPXnRB9rjccLu8XPXQ%3D%3D&u=xoaD6TMulm0Vz79q8J5JBA%3D%3D&ext=DMjZ3DQjMD8%3D&s=%2BPbNvR27dMI%3D there is the manual of Clivet heat pump (Midea) and at chapter 9 there are the explanations on wifi controller.

Something else is needed?

**Comment by kovapatrik** [comment]
The images didn't come through the email. Can you please upload them using GitHub?

**Comment by kovapatrik** [comment]
Also, in the latest beta version I've added a feature where you can download a file on the config UI discovery page, which helps me implement the plugin. Could you please attach that?

So you need to do a discovery, and when the discovery is over, you can download the file by clicking on the model number of your unit.

**Comment by kovapatrik** [comment]
One more thing: do I understand correctly that there are no current temperature displayed on this controller? I think only the target temperature is shown.

**Comment by fagallo** [comment]
I’m away from home until monday.I have installed your plugin , not beta, and try discover. It found heat pump but is “i unsupported” Monday I will try beta.—Fabio ***@***.*** giorno 6 set 2024, alle ore 19:09, Kovalovszky Patrik ***@***.***> ha scritto:﻿
Also, in the latest beta version I've added a feature where you can download a file on the config UI discovery page, which helps me implement the plugin. Could you please attach that?
So you need to do a discovery, and when the discovery is over, you can download the file by clicking on the model number of your unit.

**Comment by fagallo** [comment]
On physical controller is displayed current temperature , target temperature and external temperature.In home assistent plugin there is current temperature sensor but not have value (undefined)—Fabio ***@***.*** giorno 6 set 2024, alle ore 19:10, Kovalovszky Patrik ***@***.***> ha scritto:﻿
One more thing: do I understand correctly that there are no current temperature displayed on this controller? I think only the target temperature is shown.

**Comment by kovapatrik** [comment]
Sure thing! The discovery will identify the unit as Heat Pump WiFi Controller, but it doesn't matter as for now. I want to get that file because the original Python plugin, just as you said, didn't fetch for the current temperature and I might be able to do that using that file.

**Comment by fagallo** [comment]
A few months ago i write @georgezhao to report this problem without any response.This is the log. Please note that “current_temperature” value is null.This is state of climate:hvac_modes: off, auto, cool, heatmin_temp: 17max_temp: 30target_temp_step: 0.5current_temperature: nulltemperature: 21zone1_power: truezone2_power: falsedhw_power: falsezone1_curve: truezone2_curve: falsedisinfect: falsefast_dhw: falsezone_temp_type: false, falsezone1_room_temp_mode: truezone2_room_temp_mode: falsezone1_water_temp_mode: falsezone2_water_temp_mode: falsesilent_mode: trueeco_mode: falsetbh: falsemode: 3mode_auto: 3zone_target_temp: 40, 40dhw_target_temp: 39room_target_temp: 21zone_heating_temp_max: 65, 65zone_heating_temp_min: 35, 35zone_cooling_temp_max: 25, 25zone_cooling_temp_min: 5, 5room_temp_max: 30room_temp_min: 17dhw_temp_max: 60dhw_temp_min: 20tank_actual_temperature: 25target_temperature: 21, 21temperature_max: 30, 30temperature_min: 17, 17total_energy_consumption: 113status_heating: falsestatus_ibh: falsetotal_produced_energy: 400outdoor_temperature: 14error_code: 0icon: mdi:air-conditionerfriendly_name: Pompa di caloresupported_features: 1—Fabio ***@***.*** giorno 6 set 2024, alle ore 22:13, Kovalovszky Patrik ***@***.***> ha scritto:﻿
Sure thing! The discovery will identify the unit as Heat Pump WiFi Controller, but it doesn't matter as for now. I want to get that file because the original Python plugin, just as you said, didn't fetch for the current temperature and I might be able to do that using that file.

**Comment by kovapatrik** [comment]
Yeah, you are totally right. As I copied the logic of his plugin I've seen that it is not read out. The following attributes are available at the moment:

```
ZONE1_POWER: boolean;
ZONE2_POWER: boolean;
DHW_POWER: boolean;
ZONE1_CURVE: boolean;
ZONE2_CURVE: boolean;
DISINFECT: boolean;
FAST_DHW: boolean;
ZONE_TEMPERATURE_TYPE: boolean[];
ZONE1_ROOM_TEMPERATURE_MODE: boolean;
ZONE2_ROOM_TEMPERATURE_MODE: boolean;
ZONE1_WATER_TEMPERATURE_MODE: boolean;
ZONE2_WATER_TEMPERATURE_MODE: boolean;
MODE: number;
MODE_AUTO: number;
ZONE_TARGET_TEMPERATURE: number[];
DHW_TARGET_TEMPERATURE: number;
ROOM_TARGET_TEMPERATURE: number;
ZONE_HEATING_TEMPERATURE_MAX: number[];
ZONE_HEATING_TEMPERATURE_MIN: number[];
ZONE_COOLING_TEMPERATURE_MAX: number[];
ZONE_COOLING_TEMPERATURE_MIN: number[];
TANK_ACTUAL_TEMPERATURE?: number;
ROOM_TEMPERATURE_MAX: number;
ROOM_TEMPERATURE_MIN: number;
DHW_TEMPERATURE_MAX: number;
DHW_TEMPERATURE_MIN: number;
TARGET_TEMPERATURE: number[];
TEMPERATURE_MAX: number[];
TEMPERATURE_MIN: number[];
STATUS_HEATING?: boolean;
STATUS_DHW?: boolean;
STATUS_TBH?: boolean;
STATUS_IBH?: boolean;
TOTAL_ENERGY_CONSUMPTION?: number;
TOTAL_PRODUCED_ENERGY?: number;
OUTDOOR_TEMPERATURE?: number;
SILENT_MODE: boolean;
ECO_MODE: boolean;
TBH: boolean;
ERROR_CODE: number;
```

**Comment by kovapatrik** [comment]
By the way, if your have your unit's serial number at hand, I can download that file using that.

**Comment by kovapatrik** [comment]
Have you had a chance to do this?

**Comment by fagallo** [comment]
what should I do?

**Comment by kovapatrik** [comment]
So, you need to do the discovery process and when it's done, there is a column with your model number. That cell inside of the row where your device is, is clickable and it will download a `.lua` file, containing the script which controls the device from within the app (I guess). Can you download this and send me through email? It's `kovapatrik@gmail.com`. Alternatively, you can just send me your device's serial number (also in email, I would suggest).

**Comment by fagallo** [comment]
Sorry, but cell is non clickable. I sent you a mail with screenshot.

**Comment by kovapatrik** [comment]
Oh, you might have to update to the latest beta. Forgot to mention.

**Comment by fagallo** [comment]
Get this error : Currently used cloud provider doesn't support Lua downloading, using the default profile now...

**Comment by kovapatrik** [comment]
It should be just a warning. The file should be downloaded regarding this message.

**Comment by fagallo** [comment]
Download Lua failed: Error: Error while sending request to https://mp-prod.appsmb.com/mas/v5/app/proxy?alias=/v2/luaEncryption/luaGet: Error: Error response from API: {"msg":"移动平台Token参数缺失或请求参数名错误! [accesstoken is empy]","code":40001} at MSmartHomeCloud.apiRequest (/homebridge/node_modules/homebridge-midea-platform/dist/core/MideaCloud.js:101:23) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async MSmartHomeCloud.getProtocolLua (/homebridge/node_modules/homebridge-midea-platform/dist/core/MideaCloud.js:166:26) at async Object./downloadLua (/homebridge/node_modules/homebridge-midea-platform/homebridge-ui/server.js:155:21) at async UiServer.processRequest (/homebridge/node_modules/homebridge-midea-platform/node_modules/@homebridge/plugin-ui-utils/dist/server.js:75:30

**Comment by kovapatrik** [comment]
Okay, this looks like some type of authentication error thing. Could you please try this very same process out using the `Use default Midea SmartHome profile` option? If it doesn't work, please just send me the serial number of your device.

**Comment by kovapatrik** [comment]
Have you had a chance to try this?

**Comment by kovapatrik** [comment]
@fagallo Hello! I'm back fixing all my issues, and I want to ask if you can assist with this one.

**Comment by ucfalmi** [comment]
I might be able to help with this if @fagallo is blocked - I'd also like to control/manage my Midea Heat Pump with HomeBridge. @kovapatrik 👍

**Comment by kovapatrik** [comment]
Got it, will check on it, thanks!

**Comment by kovapatrik** [comment]
What features do you need btw? I really don't know how to display this zone1, zone2 thing.

Also @fagallo (or maybe @ucfalmi you can help as well), I only have these properties which reads temperature, but I have no clue which can be the internal temperature (if any of them is it):
```
"t4"
"tempT3"
"tempT4"
"tempTp"
"tempTwin"
"tempTwout"
"tempT1"
"tempTw2"
"tempT2"
"tempT2b"
"tempT5"
"tempTh"
"tempTa"
"tank_actual_temp"
"tempTh"
```

**Comment by fagallo** [comment]
@kovapatrik 
it should be tempTa

**Comment by ucfalmi** [comment]
I'm not sure how to decode those (could I look in the .lua?) I need heating buffer temperature (mine is set to maintain 40deg), hot water water tank temperature and hot water target temperature.  Then things like eco mode, silent mode, HW on/off, holiday mode etc.

**Comment by kovapatrik** [comment]
You can try look for things in the lua file, mostly you just need to search for the string, or keys like `zone1_heat_max_set_temp`. In your file they are all listed at the beginning of the file. If you catch something you like, let me know.

**Comment by kovapatrik** [comment]
As I can see, there is a lot of properties which are separated for zone1 and zone2. Are there props which are common in both of them? If yes, can you list them? Or create screenshots from the official app, that might also help me understand what services I should create.

Right now I think you can set the `mode` for both of them for example, so its not possible to set the zone1 mode to different from zone2 mode, am I right here?

**Comment by ucfalmi** [comment]
Does this MODBUS yaml file for a Midea Heat Pump help at all?
https://community.home-assistant.io/t/clivet-midea-heat-pump-integration-esphome-modbus-dongle/720599

**Comment by kovapatrik** [comment]
Not really, sadly but thank you! 

I got screenshots from the app, I just need time/motivation to implement this. Also I only got screenshots where there is a single zone and DHW. It would be nice to see the app when there is both zones.

**Comment by kovapatrik** [comment]
@fagallo what if there are multiple zones? Like I would think there are 2 separate room temperatures for the 2 zones, no? Or what temperature is this then?

**Comment by fagallo** [comment]
I have only One zone in my house.
2 zone it’s used when you e.g. have 2 floors. One zone for day room, and other for night room.

**Comment by kovapatrik** [comment]
I see, but my question is that what is tempTa? You said it's room temperature, but if you have multiple zone's, which temperature is it?

**Comment by kovapatrik** [comment]
Ahh okay, got it, thanks! So this should be a separate temperature sensor from everything.

**Comment by ucfalmi** [comment]
![Image](https://github.com/user-attachments/assets/8a35fbb2-94ca-4cab-96f1-d59221623003)
![Image](https://github.com/user-attachments/assets/59d5f338-9021-4cf7-943f-823407ec69cd)
![Image](https://github.com/user-attachments/assets/bc305d9a-94ce-4a84-8eb0-b4834c89cf06)

**Comment by rockett15** [comment]
Realize this is an old thread, but is there any chance of adding the fan speed to this plugin so it can be seen in Homekit?
Using this for my Senville Heat Pumps and it's working really well :)
