### ISSUE TITLE
Missing dependency "chalk"

### ISSUE THREAD

**Issue by dkerr64** [kovapatrik/homebridge-midea-platform#29]
Aarrghh... lesson in testing here.  I just tried installing the latest version on a system that had not had this plugin before.  We are missing a dependency...

```
[11/7/2023, 11:51:42 AM] [Homebridge UI] [homebridge-midea-platform] Child process ended
[11/7/2023, 11:51:49 AM] [Homebridge UI] [homebridge-midea-platform] Terminating child process...
[11/7/2023, 11:52:07 AM] [Homebridge UI] [homebridge-midea-platform] node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'chalk'
Require stack:
- /var/lib/homebridge/node_modules/homebridge-midea-platform/homebridge-ui/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-midea-platform/homebridge-ui/server.js:18:15)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/lib/homebridge/node_modules/homebridge-midea-platform/homebridge-ui/server.js'
  ]
}

Node.js v18.16.0
[11/7/2023, 11:52:07 AM] [Homebridge UI] [homebridge-midea-platform] Child process ended
```

**Comment by dkerr64** [comment]
@kovapatrik  This was entirely my fault, can you review the PR please as I think that should fix it.  Sorry.

**Comment by dkerr64** [comment]
Humm... Now I get this...

```
[11/7/2023, 12:01:32 PM] [Homebridge UI] Running Command: npm install --save homebridge-midea-platform@0.4.1
[11/7/2023, 12:01:48 PM] [Homebridge UI] [homebridge-midea-platform] /var/lib/homebridge/node_modules/homebridge-midea-platform/homebridge-ui/server.js:18
const chalk = require("chalk");
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /var/lib/homebridge/node_modules/homebridge-midea-platform/node_modules/chalk/source/index.js from /var/lib/homebridge/node_modules/homebridge-midea-platform/homebridge-ui/server.js not supported.
Instead change the require of index.js in /var/lib/homebridge/node_modules/homebridge-midea-platform/homebridge-ui/server.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-midea-platform/homebridge-ui/server.js:18:15) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.16.0
[11/7/2023, 12:01:48 PM] [Homebridge UI] [homebridge-midea-platform] Child process ended
```

**Comment by kovapatrik** [comment]
That's a weird error tho.

**Comment by dkerr64** [comment]
Yes.  Trying to decide on the best fix... https://stackoverflow.com/questions/70541068/instead-change-the-require-of-index-js-to-a-dynamic-import-which-is-available

**Comment by dkerr64** [comment]
Guidance here... https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by kovapatrik** [comment]
Do we really need chalk?

**Comment by dkerr64** [comment]
> Do we really need chalk? If we do, then we can use the latest version of Chalk v4, as v5 is ESM only.

No, I don't think I need it.  I am going to remove it and handle colors manually.  Give me an hour as I have to handle something else first

**Comment by dkerr64** [comment]
ok, I have removed the dependency on chalk. I put the necessary control characters in-line following example here... https://stackoverflow.com/questions/9781218/how-to-change-node-jss-console-font-color

**Comment by dkerr64** [comment]
Unfortunately found another (hopefully last) problem in server.js where it was not handling case where config is undefined (nothing in config.json yet).  Just submitted a PR for that.
