### ISSUE TITLE
Invalid type of key argument

### ISSUE THREAD

**Issue by sdebruyn** [kovapatrik/homebridge-midea-platform#49]
I see the following in my logs:

```
[11/19/2023, 1:15:52 PM] [homebridge-midea-platform] All configured devices added to Homebridge
TypeError: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at prepareSecretKey (node:internal/crypto/keys:596:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:139:9)
    at new Cipheriv (node:internal/crypto/cipher:249:3)
    at createCipheriv (node:crypto:141:10)
    at LocalSecurity.aes_cbc_encrpyt (/volume1/homebridge/node_modules/homebridge-midea-platform/src/core/MideaSecurity.ts:99:34)
    at LocalSecurity.encode_8370 (/volume1/homebridge/node_modules/homebridge-midea-platform/src/core/MideaSecurity.ts:171:34)
    at MideaACDevice.send_message_v3 (/volume1/homebridge/node_modules/homebridge-midea-platform/src/core/MideaDevice.ts:207:42)
    at MideaACDevice.send_message (/volume1/homebridge/node_modules/homebridge-midea-platform/src/core/MideaDevice.ts:181:18)
    at MideaACDevice.send_heartbeat (/volume1/homebridge/node_modules/homebridge-midea-platform/src/core/MideaDevice.ts:361:16)
    at MideaACDevice.run (/volume1/homebridge/node_modules/homebridge-midea-platform/src/core/MideaDevice.ts:421:18)
```

- Configured as child bridge
- 2 Midea airconditioners
- homebridge-midea-platform v0.4.10
- homebridge 1.7.0
- NodeJS v18.15.0
- installed as Synology package

I used the discovery method to add the 2 devices. The resulting config:

```json
{
            "devices": [
                {
                    "type": "Air Conditioner",
                    "name": "airco slaapkamer",
                    "id": redacted-number,
                    "advanced_options": {
                        "ip": "redacted-IP",
                        "token": "redacted-string",
                        "key": "redacted-string"
                    },
                    "AC_options": {
                        "outDoorTemp": false,
                        "ecoSwitch": false
                    }
                },
                {
                    "type": "Air Conditioner",
                    "name": "airco woonkamer",
                    "id": redacted-number,
                    "advanced_options": {
                        "ip": "redacted-IP",
                        "token": "redacted-string",
                        "key": "redacted-string"
                    },
                    "AC_options": {
                        "outDoorTemp": false,
                        "ecoSwitch": false
                    }
                }
            ],
            "platform": "midea-platform",
            "_bridge": {
                "username": "redacted-MAC",
                "port": 53943
            }
        }
```

**Comment by kovapatrik** [comment]
Is your key fields filled up with a valid value? It should be some hash, 64 characters long.

**Comment by sdebruyn** [comment]
Yes they are, the devices seem to work fine as well.

**Comment by kovapatrik** [comment]
Do you see this log one time?

**Comment by sdebruyn** [comment]
I see it multiple times when homebridge is restarting, with different stacktraces.

**Comment by kovapatrik** [comment]
So it only logs this at the startup, and later there is no such log? Can you provide a more complete log?

**Comment by sdebruyn** [comment]
I cannot reproduce them anymore. Given this, I suspect it was related to the update process.
