### ISSUE TITLE
No login possible (login failed) / discovery fails

### ISSUE THREAD

**Issue by emcepe** [kovapatrik/homebridge-midea-platform#83]
The plugin is not able to login for device discovery.

```
[5/5/2024, 6:37:18 PM] [Homebridge UI] [homebridge-midea-platform] Login failed:
Error: Error in Adding new accessory:
Error: Failed to get login ID:
Error: Failed to send request to https://mapp.appsmb.com/v1/user/login/id/get.
    at NetHomePlusCloud.apiRequest (/usr/lib/node_modules/homebridge-midea-platform/dist/core/MideaCloud.js:270:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NetHomePlusCloud.getLoginId (/usr/lib/node_modules/homebridge-midea-platform/dist/core/MideaCloud.js:40:30)
    at async NetHomePlusCloud.login (/usr/lib/node_modules/homebridge-midea-platform/dist/core/MideaCloud.js:281:30)
    at async Object./login (/usr/lib/node_modules/homebridge-midea-platform/homebridge-ui/server.js:100:11)
    at async UiServer.processRequest (/usr/lib/node_modules/homebridge-midea-platform/node_modules/@homebridge/plugin-ui-utils/dist/server.js:75:30)
    at NetHomePlusCloud.getLoginId (/usr/lib/node_modules/homebridge-midea-platform/dist/core/MideaCloud.js:50:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NetHomePlusCloud.login (/usr/lib/node_modules/homebridge-midea-platform/dist/core/MideaCloud.js:281:30)
    at async Object./login (/usr/lib/node_modules/homebridge-midea-platform/homebridge-ui/server.js:100:11)
    at async UiServer.processRequest (/usr/lib/node_modules/homebridge-midea-platform/node_modules/@homebridge/plugin-ui-utils/dist/server.js:75:30)
    at NetHomePlusCloud.login (/usr/lib/node_modules/homebridge-midea-platform/dist/core/MideaCloud.js:304:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object./login (/usr/lib/node_modules/homebridge-midea-platform/homebridge-ui/server.js:100:11)
    at async UiServer.processRequest (/usr/lib/node_modules/homebridge-midea-platform/node_modules/@homebridge/plugin-ui-utils/dist/server.js:75:30)
```

Versions before 1.0.0 can login but find nothing for whatever reason. It worked before w/o problems for a long time.

User & password are correct (Plugin homebridge-midea-air works, iOS App NetHome Plus works also)

**Environment:**
- **Plugin Version**: 1.0.5 (tried 1.0.6-beta.2 also)
- **Homebridge Version**: 1.4.1
- **Node.js Version**: 18.20.2
- **NPM Version**: 10.5.0
- **Operating System**: Raspbian Bullseye

**Comment by kovapatrik** [comment]
It should be working with `1.0.6-beta.5`, could you please test it?

**Comment by emcepe** [comment]
Hi Patrik,

thank you for the fast fix :-)

login works again but it won't find any device?! :-(

**Comment by kovapatrik** [comment]
discovering the devices is totally independent of what account you are using, so it's most likely a local network issue. are your devices on a VLAN?

**Comment by kovapatrik** [comment]
any updates on this issue?

**Comment by emcepe** [comment]
sorry 4 my late reply.

Yes, those IoT devices are all in a different VLAN but the pi has also a link to that network.

**Comment by kovapatrik** [comment]
Could you please do a discovery where you write your VLAN's IP in the "IP Addresses" field?

**Comment by emcepe** [comment]
Does not find any device.

For whatever reason the discovery will work if I change the location of the dehumidifier so the network is connected to a repeater and not to the router itself.

I don't know why - Does not make any sense to me yet.

Anyway, this issue is fixed. Thank you.
