### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by DanielSnd** [kovapatrik/homebridge-midea-platform#97]
**Describe Your Problem:**

Trying to install the plugin, I get these errors in the log below.

I just tried to install an older version 1.0.6 and didn't encounter the same errors. But also it doesn't seem to do anything and there is no plugin config info in the plugin config info window.

**Logs:**

```
[26/07/2024, 08:50:05] [Homebridge UI] Running Command: /opt/homebridge/lib/node_modules/homebridge-config-ui-x/plugin-upgrade-install.sh homebridge-midea-platform 1.1.0 /var/lib/homebridge/node_modules
[26/07/2024, 09:03:25] [Homebridge UI] [homebridge-midea-platform] Custom UI created.
[26/07/2024, 09:03:25] [Homebridge UI] [homebridge-midea-platform] node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at target._send (node:internal/child_process:879:20)
    at target.send (node:internal/child_process:752:19)
    at UiServer.ready (/var/lib/homebridge/node_modules/homebridge-midea-platform/node_modules/@homebridge/plugin-ui-utils/dist/server.js:105:17)
    at new UiServer (/var/lib/homebridge/node_modules/homebridge-midea-platform/homebridge-ui/server.js:149:10)
    at /var/lib/homebridge/node_modules/homebridge-midea-platform/homebridge-ui/server.js:276:10
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-midea-platform/homebridge-ui/server.js:277:3)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
Emitted 'error' event on process instance at:
    at node:internal/child_process:883:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v20.16.0
```

**Plugin Config:**

```json
{
    "platform": "midea-platform",
    "name": "midea-platform"
}
```

**Screenshots:**

**Environment:**

- **Plugin Version**:
- **Homebridge Version**:  Homebridge v1.8.4 (HAP v0.12.2) (Homebridge 6E1A) 
- **Node.js Version**: Node.js v20.16.0
- **NPM Version**: I don't know, where can I find that?
- **Operating System**: hb-service

**Comment by kovapatrik** [comment]
This is not an error with my plugin, but I updated the dependency with the just now released `v1.1.1`. Could you please try with this version?

**Comment by DanielSnd** [comment]
> This is not an error with my plugin, but I updated the dependency with the just now released `v1.1.1`. Could you please try with this version?

Thanks, I'll try the new version next week, I'm away from home on a trip until next tuesday.

**Comment by kovapatrik** [comment]
Have you managed to try this out?

**Comment by DanielSnd** [comment]
> Have you managed to try this out?

Sorry for the delay! Things have been busy and I forgot about it. I just saw this notification and went back to try.

I didn't try 1.1.1 specifically, I went straight to v1.1.2-beta.6 and it worked perfectly. I was able to add the AC and it works. No errors on installation.

Thank you so much! :)
